// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: template_order.proto

package template_order_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 模板上下架状态（DB: 0=下架 1=上架）
type TemplateStatus int32

const (
	TemplateStatus_TEMPLATE_STATUS_UNSPECIFIED TemplateStatus = 0
	TemplateStatus_TEMPLATE_STATUS_OFFLINE     TemplateStatus = 1
	TemplateStatus_TEMPLATE_STATUS_ONLINE      TemplateStatus = 2
)

// Enum value maps for TemplateStatus.
var (
	TemplateStatus_name = map[int32]string{
		0: "TEMPLATE_STATUS_UNSPECIFIED",
		1: "TEMPLATE_STATUS_OFFLINE",
		2: "TEMPLATE_STATUS_ONLINE",
	}
	TemplateStatus_value = map[string]int32{
		"TEMPLATE_STATUS_UNSPECIFIED": 0,
		"TEMPLATE_STATUS_OFFLINE":     1,
		"TEMPLATE_STATUS_ONLINE":      2,
	}
)

func (x TemplateStatus) Enum() *TemplateStatus {
	p := new(TemplateStatus)
	*p = x
	return p
}

func (x TemplateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_template_order_proto_enumTypes[0].Descriptor()
}

func (TemplateStatus) Type() protoreflect.EnumType {
	return &file_template_order_proto_enumTypes[0]
}

func (x TemplateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateStatus.Descriptor instead.
func (TemplateStatus) EnumDescriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{0}
}

// 订单状态（DB 值与枚举值一致）
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_UNPAID      OrderStatus = 1 // 未支付
	OrderStatus_ORDER_STATUS_PAID        OrderStatus = 2 // 已获得下载资格
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 3 // 已取消
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_UNPAID",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_UNPAID":      1,
		"ORDER_STATUS_PAID":        2,
		"ORDER_STATUS_CANCELLED":   3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_template_order_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_template_order_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{1}
}

// 订单类型（DB 值与枚举值一致）
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_FREE        OrderType = 1 // 免费
	OrderType_ORDER_TYPE_MEMBER      OrderType = 2 // 会员
	OrderType_ORDER_TYPE_RETAIL      OrderType = 3 // 零售
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_FREE",
		2: "ORDER_TYPE_MEMBER",
		3: "ORDER_TYPE_RETAIL",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_FREE":        1,
		"ORDER_TYPE_MEMBER":      2,
		"ORDER_TYPE_RETAIL":      3,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_template_order_proto_enumTypes[2].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_template_order_proto_enumTypes[2]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{2}
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=成功，非 0=业务错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_template_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_template_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_template_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_template_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 登出请求：吊销该用户所有 refresh_token（对应 FR-006）
type RevokeRefreshTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshTokensRequest) Reset() {
	*x = RevokeRefreshTokensRequest{}
	mi := &file_template_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshTokensRequest) ProtoMessage() {}

func (x *RevokeRefreshTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshTokensRequest.ProtoReflect.Descriptor instead.
func (*RevokeRefreshTokensRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeRefreshTokensRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	IsMember      bool                   `protobuf:"varint,6,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_template_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{5}
}

func (x *AuthResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsMember      bool                   `protobuf:"varint,3,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_template_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// B 端管理员检索用户（如设置会员时）
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"` // 模糊搜索（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_template_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Users         []*User                `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_template_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListUsersResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Template struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateNo           string                 `protobuf:"bytes,2,opt,name=template_no,json=templateNo,proto3" json:"template_no,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsFree               bool                   `protobuf:"varint,5,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	Price                int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"` // 分
	Status               TemplateStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=template_order.v1.TemplateStatus" json:"status,omitempty"`
	FileType             string                 `protobuf:"bytes,8,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSize             int64                  `protobuf:"varint,9,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ThumbnailDownloadUrl string                 `protobuf:"bytes,10,opt,name=thumbnail_download_url,json=thumbnailDownloadUrl,proto3" json:"thumbnail_download_url,omitempty"` // 短期预签名（仅列表/详情返回时填充）
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_template_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{9}
}

func (x *Template) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Template) GetTemplateNo() string {
	if x != nil {
		return x.TemplateNo
	}
	return ""
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Template) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *Template) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Template) GetStatus() TemplateStatus {
	if x != nil {
		return x.Status
	}
	return TemplateStatus_TEMPLATE_STATUS_UNSPECIFIED
}

func (x *Template) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Template) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Template) GetThumbnailDownloadUrl() string {
	if x != nil {
		return x.ThumbnailDownloadUrl
	}
	return ""
}

func (x *Template) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Template) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTemplateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsFree            bool                   `protobuf:"varint,3,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	Price             int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"` // 分
	OssType           string                 `protobuf:"bytes,5,opt,name=oss_type,json=ossType,proto3" json:"oss_type,omitempty"`
	BucketName        string                 `protobuf:"bytes,6,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	OriginalFilename  string                 `protobuf:"bytes,7,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	FileType          string                 `protobuf:"bytes,8,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSize          int64                  `protobuf:"varint,9,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileOssKey        string                 `protobuf:"bytes,10,opt,name=file_oss_key,json=fileOssKey,proto3" json:"file_oss_key,omitempty"`
	ThumbnailOssKey   string                 `protobuf:"bytes,11,opt,name=thumbnail_oss_key,json=thumbnailOssKey,proto3" json:"thumbnail_oss_key,omitempty"`
	ThumbnailFileSize int64                  `protobuf:"varint,12,opt,name=thumbnail_file_size,json=thumbnailFileSize,proto3" json:"thumbnail_file_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_template_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTemplateRequest) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *CreateTemplateRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTemplateRequest) GetOssType() string {
	if x != nil {
		return x.OssType
	}
	return ""
}

func (x *CreateTemplateRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *CreateTemplateRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *CreateTemplateRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *CreateTemplateRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CreateTemplateRequest) GetFileOssKey() string {
	if x != nil {
		return x.FileOssKey
	}
	return ""
}

func (x *CreateTemplateRequest) GetThumbnailOssKey() string {
	if x != nil {
		return x.ThumbnailOssKey
	}
	return ""
}

func (x *CreateTemplateRequest) GetThumbnailFileSize() int64 {
	if x != nil {
		return x.ThumbnailFileSize
	}
	return 0
}

type UpdateTemplateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsFree            bool                   `protobuf:"varint,4,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	Price             int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	ThumbnailOssKey   string                 `protobuf:"bytes,6,opt,name=thumbnail_oss_key,json=thumbnailOssKey,proto3" json:"thumbnail_oss_key,omitempty"`
	ThumbnailFileSize int64                  `protobuf:"varint,7,opt,name=thumbnail_file_size,json=thumbnailFileSize,proto3" json:"thumbnail_file_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_template_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTemplateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTemplateRequest) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *UpdateTemplateRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTemplateRequest) GetThumbnailOssKey() string {
	if x != nil {
		return x.ThumbnailOssKey
	}
	return ""
}

func (x *UpdateTemplateRequest) GetThumbnailFileSize() int64 {
	if x != nil {
		return x.ThumbnailFileSize
	}
	return 0
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	Status        *TemplateStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=template_order.v1.TemplateStatus,oneof" json:"status,omitempty"` // 未传=全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_template_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{12}
}

func (x *ListTemplatesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListTemplatesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListTemplatesRequest) GetStatus() TemplateStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return TemplateStatus_TEMPLATE_STATUS_UNSPECIFIED
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Templates     []*Template            `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_template_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{13}
}

func (x *ListTemplatesResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_template_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{14}
}

func (x *GetTemplateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Template      *Template              `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateResponse) Reset() {
	*x = GetTemplateResponse{}
	mi := &file_template_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResponse) ProtoMessage() {}

func (x *GetTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateResponse) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{15}
}

func (x *GetTemplateResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

// 上下架模板（B 端）
type UpdateTemplateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        TemplateStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=template_order.v1.TemplateStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateStatusRequest) Reset() {
	*x = UpdateTemplateStatusRequest{}
	mi := &file_template_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateStatusRequest) ProtoMessage() {}

func (x *UpdateTemplateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateStatusRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTemplateStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTemplateStatusRequest) GetStatus() TemplateStatus {
	if x != nil {
		return x.Status
	}
	return TemplateStatus_TEMPLATE_STATUS_UNSPECIFIED
}

type DownloadTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId    int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTemplateRequest) Reset() {
	*x = DownloadTemplateRequest{}
	mi := &file_template_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTemplateRequest) ProtoMessage() {}

func (x *DownloadTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTemplateRequest.ProtoReflect.Descriptor instead.
func (*DownloadTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{17}
}

func (x *DownloadTemplateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DownloadTemplateRequest) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	OrderType     OrderType              `protobuf:"varint,3,opt,name=order_type,json=orderType,proto3,enum=template_order.v1.OrderType" json:"order_type,omitempty"`
	OrderStatus   OrderStatus            `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3,enum=template_order.v1.OrderStatus" json:"order_status,omitempty"`
	PriceSnapshot int64                  `protobuf:"varint,5,opt,name=price_snapshot,json=priceSnapshot,proto3" json:"price_snapshot,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,6,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // 仅 order_status=PAID 时返回
	PaymentNo     string                 `protobuf:"bytes,7,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`       // 仅零售未支付时返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_template_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DownloadResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *DownloadResponse) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *DownloadResponse) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *DownloadResponse) GetPriceSnapshot() int64 {
	if x != nil {
		return x.PriceSnapshot
	}
	return 0
}

func (x *DownloadResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *DownloadResponse) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

type ListOrdersRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserId   *int64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`                      // 未传=不按用户筛选（管理员查全部）
	Status   *OrderStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=template_order.v1.OrderStatus,oneof" json:"status,omitempty"` // 未传=全部
	Page     *int32                 `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// 管理员用：按用户名/时间筛选
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_template_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{19}
}

func (x *ListOrdersRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListOrdersRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListOrdersRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListOrdersRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	TemplateId    int64                  `protobuf:"varint,5,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateName  string                 `protobuf:"bytes,6,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	OrderType     OrderType              `protobuf:"varint,7,opt,name=order_type,json=orderType,proto3,enum=template_order.v1.OrderType" json:"order_type,omitempty"`
	PriceSnapshot int64                  `protobuf:"varint,8,opt,name=price_snapshot,json=priceSnapshot,proto3" json:"price_snapshot,omitempty"` // 分
	Status        OrderStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=template_order.v1.OrderStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_template_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{20}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Order) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *Order) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *Order) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetPriceSnapshot() int64 {
	if x != nil {
		return x.PriceSnapshot
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_template_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{21}
}

func (x *ListOrdersResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_template_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{22}
}

func (x *CancelOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type SetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsMember      bool                   `protobuf:"varint,2,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberRequest) Reset() {
	*x = SetMemberRequest{}
	mi := &file_template_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberRequest) ProtoMessage() {}

func (x *SetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberRequest.ProtoReflect.Descriptor instead.
func (*SetMemberRequest) Descriptor() ([]byte, []int) {
	return file_template_order_proto_rawDescGZIP(), []int{23}
}

func (x *SetMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetMemberRequest) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

var File_template_order_proto protoreflect.FileDescriptor

const file_template_order_proto_rawDesc = "" +
	"\n" +
	"\x14template_order.proto\x12\x11template_order.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"5\n" +
	"\x1aRevokeRefreshTokensRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xdd\x01\n" +
	"\fAuthResponse\x123\n" +
	"\x04base\x18\x01 \x01(\v2\x1f.template_order.v1.BaseResponseR\x04base\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1b\n" +
	"\tis_member\x18\x06 \x01(\bR\bisMember\"\x8a\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tis_member\x18\x03 \x01(\bR\bisMember\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x80\x01\n" +
	"\x10ListUsersRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busernameB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"\x8d\x01\n" +
	"\x11ListUsersResponse\x123\n" +
	"\x04base\x18\x01 \x01(\v2\x1f.template_order.v1.BaseResponseR\x04base\x12-\n" +
	"\x05users\x18\x02 \x03(\v2\x17.template_order.v1.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xc1\x03\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vtemplate_no\x18\x02 \x01(\tR\n" +
	"templateNo\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x17\n" +
	"\ais_free\x18\x05 \x01(\bR\x06isFree\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x129\n" +
	"\x06status\x18\a \x01(\x0e2!.template_order.v1.TemplateStatusR\x06status\x12\x1b\n" +
	"\tfile_type\x18\b \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\t \x01(\x03R\bfileSize\x124\n" +
	"\x16thumbnail_download_url\x18\n" +
	" \x01(\tR\x14thumbnailDownloadUrl\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9d\x03\n" +
	"\x15CreateTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\ais_free\x18\x03 \x01(\bR\x06isFree\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x19\n" +
	"\boss_type\x18\x05 \x01(\tR\aossType\x12\x1f\n" +
	"\vbucket_name\x18\x06 \x01(\tR\n" +
	"bucketName\x12+\n" +
	"\x11original_filename\x18\a \x01(\tR\x10originalFilename\x12\x1b\n" +
	"\tfile_type\x18\b \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\t \x01(\x03R\bfileSize\x12 \n" +
	"\ffile_oss_key\x18\n" +
	" \x01(\tR\n" +
	"fileOssKey\x12*\n" +
	"\x11thumbnail_oss_key\x18\v \x01(\tR\x0fthumbnailOssKey\x12.\n" +
	"\x13thumbnail_file_size\x18\f \x01(\x03R\x11thumbnailFileSize\"\xe8\x01\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\ais_free\x18\x04 \x01(\bR\x06isFree\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12*\n" +
	"\x11thumbnail_oss_key\x18\x06 \x01(\tR\x0fthumbnailOssKey\x12.\n" +
	"\x13thumbnail_file_size\x18\a \x01(\x03R\x11thumbnailFileSize\"\xb3\x01\n" +
	"\x14ListTemplatesRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2!.template_order.v1.TemplateStatusH\x02R\x06status\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_sizeB\t\n" +
	"\a_status\"\x9d\x01\n" +
	"\x15ListTemplatesResponse\x123\n" +
	"\x04base\x18\x01 \x01(\v2\x1f.template_order.v1.BaseResponseR\x04base\x129\n" +
	"\ttemplates\x18\x02 \x03(\v2\x1b.template_order.v1.TemplateR\ttemplates\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"$\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x83\x01\n" +
	"\x13GetTemplateResponse\x123\n" +
	"\x04base\x18\x01 \x01(\v2\x1f.template_order.v1.BaseResponseR\x04base\x127\n" +
	"\btemplate\x18\x02 \x01(\v2\x1b.template_order.v1.TemplateR\btemplate\"h\n" +
	"\x1bUpdateTemplateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.template_order.v1.TemplateStatusR\x06status\"S\n" +
	"\x17DownloadTemplateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\"\xcb\x02\n" +
	"\x10DownloadResponse\x123\n" +
	"\x04base\x18\x01 \x01(\v2\x1f.template_order.v1.BaseResponseR\x04base\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12;\n" +
	"\n" +
	"order_type\x18\x03 \x01(\x0e2\x1c.template_order.v1.OrderTypeR\torderType\x12A\n" +
	"\forder_status\x18\x04 \x01(\x0e2\x1e.template_order.v1.OrderStatusR\vorderStatus\x12%\n" +
	"\x0eprice_snapshot\x18\x05 \x01(\x03R\rpriceSnapshot\x12!\n" +
	"\fdownload_url\x18\x06 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"payment_no\x18\a \x01(\tR\tpaymentNo\"\xe5\x02\n" +
	"\x11ListOrdersRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.template_order.v1.OrderStatusH\x01R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x03 \x01(\x05H\x02R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05H\x03R\bpageSize\x88\x01\x01\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTimeB\n" +
	"\n" +
	"\b_user_idB\t\n" +
	"\a_statusB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"\xbf\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1f\n" +
	"\vtemplate_id\x18\x05 \x01(\x03R\n" +
	"templateId\x12#\n" +
	"\rtemplate_name\x18\x06 \x01(\tR\ftemplateName\x12;\n" +
	"\n" +
	"order_type\x18\a \x01(\x0e2\x1c.template_order.v1.OrderTypeR\torderType\x12%\n" +
	"\x0eprice_snapshot\x18\b \x01(\x03R\rpriceSnapshot\x126\n" +
	"\x06status\x18\t \x01(\x0e2\x1e.template_order.v1.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x91\x01\n" +
	"\x12ListOrdersResponse\x123\n" +
	"\x04base\x18\x01 \x01(\v2\x1f.template_order.v1.BaseResponseR\x04base\x120\n" +
	"\x06orders\x18\x02 \x03(\v2\x18.template_order.v1.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"H\n" +
	"\x12CancelOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"H\n" +
	"\x10SetMemberRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tis_member\x18\x02 \x01(\bR\bisMember*j\n" +
	"\x0eTemplateStatus\x12\x1f\n" +
	"\x1bTEMPLATE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TEMPLATE_STATUS_OFFLINE\x10\x01\x12\x1a\n" +
	"\x16TEMPLATE_STATUS_ONLINE\x10\x02*w\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ORDER_STATUS_UNPAID\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x03*j\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fORDER_TYPE_FREE\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MEMBER\x10\x02\x12\x15\n" +
	"\x11ORDER_TYPE_RETAIL\x10\x032\x99\n" +
	"\n" +
	"\x14TemplateOrderService\x12O\n" +
	"\bRegister\x12\".template_order.v1.RegisterRequest\x1a\x1f.template_order.v1.AuthResponse\x12I\n" +
	"\x05Login\x12\x1f.template_order.v1.LoginRequest\x1a\x1f.template_order.v1.AuthResponse\x12W\n" +
	"\fRefreshToken\x12&.template_order.v1.RefreshTokenRequest\x1a\x1f.template_order.v1.AuthResponse\x12e\n" +
	"\x13RevokeRefreshTokens\x12-.template_order.v1.RevokeRefreshTokensRequest\x1a\x1f.template_order.v1.BaseResponse\x12V\n" +
	"\tListUsers\x12#.template_order.v1.ListUsersRequest\x1a$.template_order.v1.ListUsersResponse\x12[\n" +
	"\x0eCreateTemplate\x12(.template_order.v1.CreateTemplateRequest\x1a\x1f.template_order.v1.BaseResponse\x12[\n" +
	"\x0eUpdateTemplate\x12(.template_order.v1.UpdateTemplateRequest\x1a\x1f.template_order.v1.BaseResponse\x12b\n" +
	"\rListTemplates\x12'.template_order.v1.ListTemplatesRequest\x1a(.template_order.v1.ListTemplatesResponse\x12\\\n" +
	"\vGetTemplate\x12%.template_order.v1.GetTemplateRequest\x1a&.template_order.v1.GetTemplateResponse\x12g\n" +
	"\x14UpdateTemplateStatus\x12..template_order.v1.UpdateTemplateStatusRequest\x1a\x1f.template_order.v1.BaseResponse\x12c\n" +
	"\x10DownloadTemplate\x12*.template_order.v1.DownloadTemplateRequest\x1a#.template_order.v1.DownloadResponse\x12Y\n" +
	"\n" +
	"ListOrders\x12$.template_order.v1.ListOrdersRequest\x1a%.template_order.v1.ListOrdersResponse\x12U\n" +
	"\vCancelOrder\x12%.template_order.v1.CancelOrderRequest\x1a\x1f.template_order.v1.BaseResponse\x12Q\n" +
	"\tSetMember\x12#.template_order.v1.SetMemberRequest\x1a\x1f.template_order.v1.BaseResponseB?Z=template-mall/TemplateOrderServer/api/proto;template_order_pbb\x06proto3"

var (
	file_template_order_proto_rawDescOnce sync.Once
	file_template_order_proto_rawDescData []byte
)

func file_template_order_proto_rawDescGZIP() []byte {
	file_template_order_proto_rawDescOnce.Do(func() {
		file_template_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_template_order_proto_rawDesc), len(file_template_order_proto_rawDesc)))
	})
	return file_template_order_proto_rawDescData
}

var file_template_order_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_template_order_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_template_order_proto_goTypes = []any{
	(TemplateStatus)(0),                 // 0: template_order.v1.TemplateStatus
	(OrderStatus)(0),                    // 1: template_order.v1.OrderStatus
	(OrderType)(0),                      // 2: template_order.v1.OrderType
	(*BaseResponse)(nil),                // 3: template_order.v1.BaseResponse
	(*RegisterRequest)(nil),             // 4: template_order.v1.RegisterRequest
	(*LoginRequest)(nil),                // 5: template_order.v1.LoginRequest
	(*RefreshTokenRequest)(nil),         // 6: template_order.v1.RefreshTokenRequest
	(*RevokeRefreshTokensRequest)(nil),  // 7: template_order.v1.RevokeRefreshTokensRequest
	(*AuthResponse)(nil),                // 8: template_order.v1.AuthResponse
	(*User)(nil),                        // 9: template_order.v1.User
	(*ListUsersRequest)(nil),            // 10: template_order.v1.ListUsersRequest
	(*ListUsersResponse)(nil),           // 11: template_order.v1.ListUsersResponse
	(*Template)(nil),                    // 12: template_order.v1.Template
	(*CreateTemplateRequest)(nil),       // 13: template_order.v1.CreateTemplateRequest
	(*UpdateTemplateRequest)(nil),       // 14: template_order.v1.UpdateTemplateRequest
	(*ListTemplatesRequest)(nil),        // 15: template_order.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),       // 16: template_order.v1.ListTemplatesResponse
	(*GetTemplateRequest)(nil),          // 17: template_order.v1.GetTemplateRequest
	(*GetTemplateResponse)(nil),         // 18: template_order.v1.GetTemplateResponse
	(*UpdateTemplateStatusRequest)(nil), // 19: template_order.v1.UpdateTemplateStatusRequest
	(*DownloadTemplateRequest)(nil),     // 20: template_order.v1.DownloadTemplateRequest
	(*DownloadResponse)(nil),            // 21: template_order.v1.DownloadResponse
	(*ListOrdersRequest)(nil),           // 22: template_order.v1.ListOrdersRequest
	(*Order)(nil),                       // 23: template_order.v1.Order
	(*ListOrdersResponse)(nil),          // 24: template_order.v1.ListOrdersResponse
	(*CancelOrderRequest)(nil),          // 25: template_order.v1.CancelOrderRequest
	(*SetMemberRequest)(nil),            // 26: template_order.v1.SetMemberRequest
	(*timestamppb.Timestamp)(nil),       // 27: google.protobuf.Timestamp
}
var file_template_order_proto_depIdxs = []int32{
	3,  // 0: template_order.v1.AuthResponse.base:type_name -> template_order.v1.BaseResponse
	27, // 1: template_order.v1.User.created_at:type_name -> google.protobuf.Timestamp
	3,  // 2: template_order.v1.ListUsersResponse.base:type_name -> template_order.v1.BaseResponse
	9,  // 3: template_order.v1.ListUsersResponse.users:type_name -> template_order.v1.User
	0,  // 4: template_order.v1.Template.status:type_name -> template_order.v1.TemplateStatus
	27, // 5: template_order.v1.Template.created_at:type_name -> google.protobuf.Timestamp
	27, // 6: template_order.v1.Template.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: template_order.v1.ListTemplatesRequest.status:type_name -> template_order.v1.TemplateStatus
	3,  // 8: template_order.v1.ListTemplatesResponse.base:type_name -> template_order.v1.BaseResponse
	12, // 9: template_order.v1.ListTemplatesResponse.templates:type_name -> template_order.v1.Template
	3,  // 10: template_order.v1.GetTemplateResponse.base:type_name -> template_order.v1.BaseResponse
	12, // 11: template_order.v1.GetTemplateResponse.template:type_name -> template_order.v1.Template
	0,  // 12: template_order.v1.UpdateTemplateStatusRequest.status:type_name -> template_order.v1.TemplateStatus
	3,  // 13: template_order.v1.DownloadResponse.base:type_name -> template_order.v1.BaseResponse
	2,  // 14: template_order.v1.DownloadResponse.order_type:type_name -> template_order.v1.OrderType
	1,  // 15: template_order.v1.DownloadResponse.order_status:type_name -> template_order.v1.OrderStatus
	1,  // 16: template_order.v1.ListOrdersRequest.status:type_name -> template_order.v1.OrderStatus
	27, // 17: template_order.v1.ListOrdersRequest.start_time:type_name -> google.protobuf.Timestamp
	27, // 18: template_order.v1.ListOrdersRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 19: template_order.v1.Order.order_type:type_name -> template_order.v1.OrderType
	1,  // 20: template_order.v1.Order.status:type_name -> template_order.v1.OrderStatus
	27, // 21: template_order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	27, // 22: template_order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 23: template_order.v1.ListOrdersResponse.base:type_name -> template_order.v1.BaseResponse
	23, // 24: template_order.v1.ListOrdersResponse.orders:type_name -> template_order.v1.Order
	4,  // 25: template_order.v1.TemplateOrderService.Register:input_type -> template_order.v1.RegisterRequest
	5,  // 26: template_order.v1.TemplateOrderService.Login:input_type -> template_order.v1.LoginRequest
	6,  // 27: template_order.v1.TemplateOrderService.RefreshToken:input_type -> template_order.v1.RefreshTokenRequest
	7,  // 28: template_order.v1.TemplateOrderService.RevokeRefreshTokens:input_type -> template_order.v1.RevokeRefreshTokensRequest
	10, // 29: template_order.v1.TemplateOrderService.ListUsers:input_type -> template_order.v1.ListUsersRequest
	13, // 30: template_order.v1.TemplateOrderService.CreateTemplate:input_type -> template_order.v1.CreateTemplateRequest
	14, // 31: template_order.v1.TemplateOrderService.UpdateTemplate:input_type -> template_order.v1.UpdateTemplateRequest
	15, // 32: template_order.v1.TemplateOrderService.ListTemplates:input_type -> template_order.v1.ListTemplatesRequest
	17, // 33: template_order.v1.TemplateOrderService.GetTemplate:input_type -> template_order.v1.GetTemplateRequest
	19, // 34: template_order.v1.TemplateOrderService.UpdateTemplateStatus:input_type -> template_order.v1.UpdateTemplateStatusRequest
	20, // 35: template_order.v1.TemplateOrderService.DownloadTemplate:input_type -> template_order.v1.DownloadTemplateRequest
	22, // 36: template_order.v1.TemplateOrderService.ListOrders:input_type -> template_order.v1.ListOrdersRequest
	25, // 37: template_order.v1.TemplateOrderService.CancelOrder:input_type -> template_order.v1.CancelOrderRequest
	26, // 38: template_order.v1.TemplateOrderService.SetMember:input_type -> template_order.v1.SetMemberRequest
	8,  // 39: template_order.v1.TemplateOrderService.Register:output_type -> template_order.v1.AuthResponse
	8,  // 40: template_order.v1.TemplateOrderService.Login:output_type -> template_order.v1.AuthResponse
	8,  // 41: template_order.v1.TemplateOrderService.RefreshToken:output_type -> template_order.v1.AuthResponse
	3,  // 42: template_order.v1.TemplateOrderService.RevokeRefreshTokens:output_type -> template_order.v1.BaseResponse
	11, // 43: template_order.v1.TemplateOrderService.ListUsers:output_type -> template_order.v1.ListUsersResponse
	3,  // 44: template_order.v1.TemplateOrderService.CreateTemplate:output_type -> template_order.v1.BaseResponse
	3,  // 45: template_order.v1.TemplateOrderService.UpdateTemplate:output_type -> template_order.v1.BaseResponse
	16, // 46: template_order.v1.TemplateOrderService.ListTemplates:output_type -> template_order.v1.ListTemplatesResponse
	18, // 47: template_order.v1.TemplateOrderService.GetTemplate:output_type -> template_order.v1.GetTemplateResponse
	3,  // 48: template_order.v1.TemplateOrderService.UpdateTemplateStatus:output_type -> template_order.v1.BaseResponse
	21, // 49: template_order.v1.TemplateOrderService.DownloadTemplate:output_type -> template_order.v1.DownloadResponse
	24, // 50: template_order.v1.TemplateOrderService.ListOrders:output_type -> template_order.v1.ListOrdersResponse
	3,  // 51: template_order.v1.TemplateOrderService.CancelOrder:output_type -> template_order.v1.BaseResponse
	3,  // 52: template_order.v1.TemplateOrderService.SetMember:output_type -> template_order.v1.BaseResponse
	39, // [39:53] is the sub-list for method output_type
	25, // [25:39] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_template_order_proto_init() }
func file_template_order_proto_init() {
	if File_template_order_proto != nil {
		return
	}
	file_template_order_proto_msgTypes[7].OneofWrappers = []any{}
	file_template_order_proto_msgTypes[12].OneofWrappers = []any{}
	file_template_order_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_template_order_proto_rawDesc), len(file_template_order_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_template_order_proto_goTypes,
		DependencyIndexes: file_template_order_proto_depIdxs,
		EnumInfos:         file_template_order_proto_enumTypes,
		MessageInfos:      file_template_order_proto_msgTypes,
	}.Build()
	File_template_order_proto = out.File
	file_template_order_proto_goTypes = nil
	file_template_order_proto_depIdxs = nil
}
